### ISSUE TITLE
when token expired, exporter occurred unauthorized error

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-community/cf_exporter#12]
I using version Prometheus BOSH Release v14.0.0

occurs repeatedly every week and resolved at monit restart cf-exporter
It seems to be related parameter (uaa.clients.cf.refresh_token_validity: 604800)

How about your thinks?

time="2017-04-06T00:15:36Z" level=error msg="Error while listing services: Error requesting services Get https://xxxxxxx/v2/services?: oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"invalid_token\",\"error_description\":\"The token expired, was revoked, or the token ID is incorrect: 3c25986e86ff486aa211bf88594b6d50-r\"}" source="services_collector.go:142"

**Comment by shinji62** [comment]
+1 confirming this issue. @frodenas

**Comment by frodenas** [comment]
This is interesting because I thought it was solved (see #1). In fact, I checked one of my environments and the `cf_exporter` has been running for 32 days without any issue:

```
Process 'cf_exporter'
  status                            running
  monitoring status                 monitored
  pid                               4567
  parent pid                        1
  uptime                            32d 20h 26m
  children                          2
  memory kilobytes                  32324
  memory kilobytes total            32324
  memory percent                    0.7%
  memory percent total              0.7%
  cpu percent                       0.0%
  cpu percent total                 0.0%
  data collected                    Tue Apr 11 18:36:32 2017
```
Worth noting the above exporter is using a client with no explicit `refresh_token_validity`, so it should use the default one (set to `2592000` seconds or `30` days).

```
uaac client get prometheus
  scope: uaa.none
  client_id: prometheus
  resource_ids: none
  authorized_grant_types: refresh_token client_credentials
  autoapprove:
  authorities: doppler.firehose cloud_controller.admin
  name: prometheus
  lastmodified: 1488469666000
```

How are you configuring the `cf_exporter`? Using `user` & `password` or using `client-id` & `client-secret`?
